// Package metricsapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package metricsapi

import (
	"context"
	"fmt"
	"time"

	"github.com/gofiber/fiber/v3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for APIErrorCode.
const (
	Conflict      APIErrorCode = "conflict"
	Forbidden     APIErrorCode = "forbidden"
	InternalError APIErrorCode = "internal_error"
	InvalidInput  APIErrorCode = "invalid_input"
	NotFound      APIErrorCode = "not_found"
	RateLimited   APIErrorCode = "rate_limited"
	RequestFailed APIErrorCode = "request_failed"
	Unauthorized  APIErrorCode = "unauthorized"
	Unavailable   APIErrorCode = "unavailable"
)

// Defines values for ProviderTransferDirection.
const (
	Download ProviderTransferDirection = "download"
	Upload   ProviderTransferDirection = "upload"
)

// Defines values for ProviderTransferReconciliationStatus.
const (
	All       ProviderTransferReconciliationStatus = "all"
	Ambiguous ProviderTransferReconciliationStatus = "ambiguous"
	Matched   ProviderTransferReconciliationStatus = "matched"
	Unmatched ProviderTransferReconciliationStatus = "unmatched"
)

// Defines values for TransferBreakdownResponseGroupBy.
const (
	TransferBreakdownResponseGroupByObject   TransferBreakdownResponseGroupBy = "object"
	TransferBreakdownResponseGroupByProvider TransferBreakdownResponseGroupBy = "provider"
	TransferBreakdownResponseGroupByScope    TransferBreakdownResponseGroupBy = "scope"
	TransferBreakdownResponseGroupByUser     TransferBreakdownResponseGroupBy = "user"
)

// Defines values for GetTransferBreakdownParamsGroupBy.
const (
	GetTransferBreakdownParamsGroupByObject   GetTransferBreakdownParamsGroupBy = "object"
	GetTransferBreakdownParamsGroupByProvider GetTransferBreakdownParamsGroupBy = "provider"
	GetTransferBreakdownParamsGroupByScope    GetTransferBreakdownParamsGroupBy = "scope"
	GetTransferBreakdownParamsGroupByUser     GetTransferBreakdownParamsGroupBy = "user"
)

// APIError A stable Syfon API error.
type APIError struct {
	// Code Stable machine-readable error code.
	Code APIErrorCode `json:"code"`

	// Message Human-readable error message.
	Message string `json:"message"`

	// Msg GA4GH-compatible alias for message.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	Msg *string `json:"msg,omitempty"`

	// RequestId Request identifier for support and log correlation.
	RequestId *string `json:"request_id,omitempty"`

	// Status HTTP response status.
	Status int `json:"status"`
}

// APIErrorCode Stable machine-readable error code.
type APIErrorCode string

// FileUsage defines model for FileUsage.
type FileUsage struct {
	DownloadCount    *int64     `json:"download_count,omitempty"`
	LastAccessTime   *time.Time `json:"last_access_time"`
	LastDownloadTime *time.Time `json:"last_download_time"`
	LastUploadTime   *time.Time `json:"last_upload_time"`
	Name             *string    `json:"name,omitempty"`
	ObjectId         *string    `json:"object_id,omitempty"`
	Size             *int64     `json:"size,omitempty"`
	UploadCount      *int64     `json:"upload_count,omitempty"`
}

// FileUsageBulkRequest defines model for FileUsageBulkRequest.
type FileUsageBulkRequest struct {
	InactiveDays *int     `json:"inactive_days,omitempty"`
	ObjectIds    []string `json:"object_ids"`
}

// FileUsageSummary defines model for FileUsageSummary.
type FileUsageSummary struct {
	InactiveFileCount       *int64     `json:"inactive_file_count,omitempty"`
	RecordCount             *int64     `json:"record_count,omitempty"`
	RecordLatestUpdatedTime *time.Time `json:"record_latest_updated_time"`
	TotalDownloads          *int64     `json:"total_downloads,omitempty"`
	TotalFiles              *int64     `json:"total_files,omitempty"`
	TotalUploads            *int64     `json:"total_uploads,omitempty"`
}

// MetricsListResponse defines model for MetricsListResponse.
type MetricsListResponse struct {
	Data   *[]FileUsage `json:"data,omitempty"`
	Limit  *int         `json:"limit,omitempty"`
	Offset *int         `json:"offset,omitempty"`
}

// ProviderTransferDirection defines model for ProviderTransferDirection.
type ProviderTransferDirection string

// ProviderTransferEvent defines model for ProviderTransferEvent.
type ProviderTransferEvent struct {
	AccessGrantId    *string                   `json:"access_grant_id,omitempty"`
	AccessId         *string                   `json:"access_id,omitempty"`
	ActorEmail       *string                   `json:"actor_email,omitempty"`
	ActorSubject     *string                   `json:"actor_subject,omitempty"`
	AuthMode         *string                   `json:"auth_mode,omitempty"`
	Bucket           string                    `json:"bucket"`
	BytesTransferred int64                     `json:"bytes_transferred"`
	Direction        ProviderTransferDirection `json:"direction"`
	EventTime        *time.Time                `json:"event_time,omitempty"`
	HttpMethod       *string                   `json:"http_method,omitempty"`
	HttpStatus       *int                      `json:"http_status,omitempty"`

	// ObjectId DRS object DID when known.
	ObjectId     *string `json:"object_id,omitempty"`
	ObjectKey    *string `json:"object_key,omitempty"`
	ObjectSize   *int64  `json:"object_size,omitempty"`
	Organization *string `json:"organization,omitempty"`
	Project      *string `json:"project,omitempty"`
	Provider     string  `json:"provider"`

	// ProviderEventId Provider/importer idempotency key.
	ProviderEventId      string                                `json:"provider_event_id"`
	ProviderRequestId    *string                               `json:"provider_request_id,omitempty"`
	RangeEnd             *int64                                `json:"range_end"`
	RangeStart           *int64                                `json:"range_start"`
	RawEventRef          *string                               `json:"raw_event_ref,omitempty"`
	ReconciliationStatus *ProviderTransferReconciliationStatus `json:"reconciliation_status,omitempty"`
	RequestId            *string                               `json:"request_id,omitempty"`
	RequesterPrincipal   *string                               `json:"requester_principal,omitempty"`
	Sha256               *string                               `json:"sha256,omitempty"`
	SourceIp             *string                               `json:"source_ip,omitempty"`
	StorageUrl           *string                               `json:"storage_url,omitempty"`
	UserAgent            *string                               `json:"user_agent,omitempty"`
}

// ProviderTransferEventsRequest defines model for ProviderTransferEventsRequest.
type ProviderTransferEventsRequest struct {
	Events []ProviderTransferEvent `json:"events"`
}

// ProviderTransferReconciliationStatus defines model for ProviderTransferReconciliationStatus.
type ProviderTransferReconciliationStatus string

// TransferAttributionBreakdown defines model for TransferAttributionBreakdown.
type TransferAttributionBreakdown struct {
	ActorEmail       *string    `json:"actor_email,omitempty"`
	ActorSubject     *string    `json:"actor_subject,omitempty"`
	Bucket           *string    `json:"bucket,omitempty"`
	BytesDownloaded  *int64     `json:"bytes_downloaded,omitempty"`
	BytesRequested   *int64     `json:"bytes_requested,omitempty"`
	BytesUploaded    *int64     `json:"bytes_uploaded,omitempty"`
	EventCount       *int64     `json:"event_count,omitempty"`
	Key              *string    `json:"key,omitempty"`
	LastTransferTime *time.Time `json:"last_transfer_time"`
	Organization     *string    `json:"organization,omitempty"`
	Project          *string    `json:"project,omitempty"`
	Provider         *string    `json:"provider,omitempty"`
	Sha256           *string    `json:"sha256,omitempty"`
}

// TransferAttributionSummary defines model for TransferAttributionSummary.
type TransferAttributionSummary struct {
	AccessIssuedCount  *int64                    `json:"access_issued_count,omitempty"`
	BytesDownloaded    *int64                    `json:"bytes_downloaded,omitempty"`
	BytesRequested     *int64                    `json:"bytes_requested,omitempty"`
	BytesUploaded      *int64                    `json:"bytes_uploaded,omitempty"`
	DownloadEventCount *int64                    `json:"download_event_count,omitempty"`
	EventCount         *int64                    `json:"event_count,omitempty"`
	Freshness          *TransferMetricsFreshness `json:"freshness,omitempty"`
	UploadEventCount   *int64                    `json:"upload_event_count,omitempty"`
}

// TransferBreakdownResponse defines model for TransferBreakdownResponse.
type TransferBreakdownResponse struct {
	Data      *[]TransferAttributionBreakdown   `json:"data,omitempty"`
	Freshness *TransferMetricsFreshness         `json:"freshness,omitempty"`
	GroupBy   *TransferBreakdownResponseGroupBy `json:"group_by,omitempty"`
}

// TransferBreakdownResponseGroupBy defines model for TransferBreakdownResponse.GroupBy.
type TransferBreakdownResponseGroupBy string

// TransferEventsRecordedResponse defines model for TransferEventsRecordedResponse.
type TransferEventsRecordedResponse struct {
	Recorded *int `json:"recorded,omitempty"`
}

// TransferMetricsFreshness defines model for TransferMetricsFreshness.
type TransferMetricsFreshness struct {
	IsStale             *bool      `json:"is_stale,omitempty"`
	LatestCompletedSync *time.Time `json:"latest_completed_sync"`
	MissingBuckets      *[]string  `json:"missing_buckets,omitempty"`
	RequiredFrom        *time.Time `json:"required_from"`
	RequiredTo          *time.Time `json:"required_to"`
}

// AllowStale defines model for AllowStale.
type AllowStale = bool

// Bucket defines model for Bucket.
type Bucket = string

// Direction defines model for Direction.
type Direction = ProviderTransferDirection

// From defines model for From.
type From = time.Time

// Organization defines model for Organization.
type Organization = string

// Project defines model for Project.
type Project = string

// Provider defines model for Provider.
type Provider = string

// ReconciliationStatus defines model for ReconciliationStatus.
type ReconciliationStatus = ProviderTransferReconciliationStatus

// SHA256 defines model for SHA256.
type SHA256 = string

// To defines model for To.
type To = time.Time

// User defines model for User.
type User = string

// ListMetricsFilesParams defines parameters for ListMetricsFiles.
type ListMetricsFilesParams struct {
	Limit        *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset       *int `form:"offset,omitempty" json:"offset,omitempty"`
	InactiveDays *int `form:"inactive_days,omitempty" json:"inactive_days,omitempty"`

	// Organization Organization/program scope filter.
	Organization *Organization `form:"organization,omitempty" json:"organization,omitempty"`

	// Project Project scope filter. Requires organization when set.
	Project *Project `form:"project,omitempty" json:"project,omitempty"`
}

// BulkMetricsFilesParams defines parameters for BulkMetricsFiles.
type BulkMetricsFilesParams struct {
	// Organization Organization/program scope filter.
	Organization *Organization `form:"organization,omitempty" json:"organization,omitempty"`

	// Project Project scope filter. Requires organization when set.
	Project *Project `form:"project,omitempty" json:"project,omitempty"`
}

// GetMetricsFileParams defines parameters for GetMetricsFile.
type GetMetricsFileParams struct {
	// Organization Organization/program scope filter.
	Organization *Organization `form:"organization,omitempty" json:"organization,omitempty"`

	// Project Project scope filter. Requires organization when set.
	Project *Project `form:"project,omitempty" json:"project,omitempty"`
}

// RecordProviderTransferEventsParams defines parameters for RecordProviderTransferEvents.
type RecordProviderTransferEventsParams struct {
	// Organization Organization/program scope filter.
	Organization *Organization `form:"organization,omitempty" json:"organization,omitempty"`

	// Project Project scope filter. Requires organization when set.
	Project *Project `form:"project,omitempty" json:"project,omitempty"`
}

// GetMetricsSummaryParams defines parameters for GetMetricsSummary.
type GetMetricsSummaryParams struct {
	InactiveDays *int `form:"inactive_days,omitempty" json:"inactive_days,omitempty"`

	// Organization Organization/program scope filter.
	Organization *Organization `form:"organization,omitempty" json:"organization,omitempty"`

	// Project Project scope filter. Requires organization when set.
	Project *Project `form:"project,omitempty" json:"project,omitempty"`
}

// GetTransferBreakdownParams defines parameters for GetTransferBreakdown.
type GetTransferBreakdownParams struct {
	// Organization Organization/program scope filter.
	Organization *Organization `form:"organization,omitempty" json:"organization,omitempty"`

	// Project Project scope filter. Requires organization when set.
	Project              *Project              `form:"project,omitempty" json:"project,omitempty"`
	Direction            *Direction            `form:"direction,omitempty" json:"direction,omitempty"`
	ReconciliationStatus *ReconciliationStatus `form:"reconciliation_status,omitempty" json:"reconciliation_status,omitempty"`
	From                 *From                 `form:"from,omitempty" json:"from,omitempty"`
	To                   *To                   `form:"to,omitempty" json:"to,omitempty"`
	Provider             *Provider             `form:"provider,omitempty" json:"provider,omitempty"`
	Bucket               *Bucket               `form:"bucket,omitempty" json:"bucket,omitempty"`
	Sha256               *SHA256               `form:"sha256,omitempty" json:"sha256,omitempty"`

	// User Actor email or subject filter.
	User *User `form:"user,omitempty" json:"user,omitempty"`

	// AllowStale Deprecated. Transfer metrics always return persisted provider events with freshness metadata, including missing sync windows and latest completed sync time.
	AllowStale *AllowStale                        `form:"allow_stale,omitempty" json:"allow_stale,omitempty"`
	GroupBy    *GetTransferBreakdownParamsGroupBy `form:"group_by,omitempty" json:"group_by,omitempty"`
}

// GetTransferBreakdownParamsGroupBy defines parameters for GetTransferBreakdown.
type GetTransferBreakdownParamsGroupBy string

// GetTransferSummaryParams defines parameters for GetTransferSummary.
type GetTransferSummaryParams struct {
	// Organization Organization/program scope filter.
	Organization *Organization `form:"organization,omitempty" json:"organization,omitempty"`

	// Project Project scope filter. Requires organization when set.
	Project              *Project              `form:"project,omitempty" json:"project,omitempty"`
	Direction            *Direction            `form:"direction,omitempty" json:"direction,omitempty"`
	ReconciliationStatus *ReconciliationStatus `form:"reconciliation_status,omitempty" json:"reconciliation_status,omitempty"`
	From                 *From                 `form:"from,omitempty" json:"from,omitempty"`
	To                   *To                   `form:"to,omitempty" json:"to,omitempty"`
	Provider             *Provider             `form:"provider,omitempty" json:"provider,omitempty"`
	Bucket               *Bucket               `form:"bucket,omitempty" json:"bucket,omitempty"`
	Sha256               *SHA256               `form:"sha256,omitempty" json:"sha256,omitempty"`

	// User Actor email or subject filter.
	User *User `form:"user,omitempty" json:"user,omitempty"`

	// AllowStale Deprecated. Transfer metrics always return persisted provider events with freshness metadata, including missing sync windows and latest completed sync time.
	AllowStale *AllowStale `form:"allow_stale,omitempty" json:"allow_stale,omitempty"`
}

// BulkMetricsFilesJSONRequestBody defines body for BulkMetricsFiles for application/json ContentType.
type BulkMetricsFilesJSONRequestBody = FileUsageBulkRequest

// RecordProviderTransferEventsJSONRequestBody defines body for RecordProviderTransferEvents for application/json ContentType.
type RecordProviderTransferEventsJSONRequestBody = ProviderTransferEventsRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /index/v1/metrics/files)
	ListMetricsFiles(c fiber.Ctx, params ListMetricsFilesParams) error

	// (POST /index/v1/metrics/files/bulk)
	BulkMetricsFiles(c fiber.Ctx, params BulkMetricsFilesParams) error

	// (GET /index/v1/metrics/files/{object_id})
	GetMetricsFile(c fiber.Ctx, objectId string, params GetMetricsFileParams) error
	// Record provider-observed transfer events
	// (POST /index/v1/metrics/provider-transfer-events)
	RecordProviderTransferEvents(c fiber.Ctx, params RecordProviderTransferEventsParams) error

	// (GET /index/v1/metrics/summary)
	GetMetricsSummary(c fiber.Ctx, params GetMetricsSummaryParams) error
	// Group transfer attribution events
	// (GET /index/v1/metrics/transfers/breakdown)
	GetTransferBreakdown(c fiber.Ctx, params GetTransferBreakdownParams) error
	// Summarize transfer attribution events
	// (GET /index/v1/metrics/transfers/summary)
	GetTransferSummary(c fiber.Ctx, params GetTransferSummaryParams) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// ListMetricsFiles operation middleware
func (siw *ServerInterfaceWrapper) ListMetricsFiles(c fiber.Ctx) error {
	var err error
	var params ListMetricsFilesParams

	// ------------- Optional query parameter "limit" -------------
	if paramValue := c.Query("limit"); paramValue != "" {

		var value int
		err = runtime.BindStyledParameterWithOptions("form", "limit", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
		}
		params.Limit = &value

	}
	// ------------- Optional query parameter "offset" -------------
	if paramValue := c.Query("offset"); paramValue != "" {

		var value int
		err = runtime.BindStyledParameterWithOptions("form", "offset", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
		}
		params.Offset = &value

	}
	// ------------- Optional query parameter "inactive_days" -------------
	if paramValue := c.Query("inactive_days"); paramValue != "" {

		var value int
		err = runtime.BindStyledParameterWithOptions("form", "inactive_days", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter inactive_days: %w", err).Error())
		}
		params.InactiveDays = &value

	}
	// ------------- Optional query parameter "organization" -------------
	if paramValue := c.Query("organization"); paramValue != "" {

		var value Organization
		err = runtime.BindStyledParameterWithOptions("form", "organization", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter organization: %w", err).Error())
		}
		params.Organization = &value

	}
	// ------------- Optional query parameter "project" -------------
	if paramValue := c.Query("project"); paramValue != "" {

		var value Project
		err = runtime.BindStyledParameterWithOptions("form", "project", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter project: %w", err).Error())
		}
		params.Project = &value

	}

	return siw.Handler.ListMetricsFiles(c, params)
}

// BulkMetricsFiles operation middleware
func (siw *ServerInterfaceWrapper) BulkMetricsFiles(c fiber.Ctx) error {
	var err error
	var params BulkMetricsFilesParams

	// ------------- Optional query parameter "organization" -------------
	if paramValue := c.Query("organization"); paramValue != "" {

		var value Organization
		err = runtime.BindStyledParameterWithOptions("form", "organization", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter organization: %w", err).Error())
		}
		params.Organization = &value

	}
	// ------------- Optional query parameter "project" -------------
	if paramValue := c.Query("project"); paramValue != "" {

		var value Project
		err = runtime.BindStyledParameterWithOptions("form", "project", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter project: %w", err).Error())
		}
		params.Project = &value

	}

	return siw.Handler.BulkMetricsFiles(c, params)
}

// GetMetricsFile operation middleware
func (siw *ServerInterfaceWrapper) GetMetricsFile(c fiber.Ctx) error {
	var err error
	var params GetMetricsFileParams

	// ------------- Path parameter "object_id" -------------
	var objectId string

	err = runtime.BindStyledParameterWithOptions("simple", "object_id", c.Params("object_id"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter object_id: %w", err).Error())
	}

	// ------------- Optional query parameter "organization" -------------
	if paramValue := c.Query("organization"); paramValue != "" {

		var value Organization
		err = runtime.BindStyledParameterWithOptions("form", "organization", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter organization: %w", err).Error())
		}
		params.Organization = &value

	}
	// ------------- Optional query parameter "project" -------------
	if paramValue := c.Query("project"); paramValue != "" {

		var value Project
		err = runtime.BindStyledParameterWithOptions("form", "project", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter project: %w", err).Error())
		}
		params.Project = &value

	}

	return siw.Handler.GetMetricsFile(c, objectId, params)
}

// RecordProviderTransferEvents operation middleware
func (siw *ServerInterfaceWrapper) RecordProviderTransferEvents(c fiber.Ctx) error {
	var err error
	var params RecordProviderTransferEventsParams

	// ------------- Optional query parameter "organization" -------------
	if paramValue := c.Query("organization"); paramValue != "" {

		var value Organization
		err = runtime.BindStyledParameterWithOptions("form", "organization", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter organization: %w", err).Error())
		}
		params.Organization = &value

	}
	// ------------- Optional query parameter "project" -------------
	if paramValue := c.Query("project"); paramValue != "" {

		var value Project
		err = runtime.BindStyledParameterWithOptions("form", "project", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter project: %w", err).Error())
		}
		params.Project = &value

	}

	return siw.Handler.RecordProviderTransferEvents(c, params)
}

// GetMetricsSummary operation middleware
func (siw *ServerInterfaceWrapper) GetMetricsSummary(c fiber.Ctx) error {
	var err error
	var params GetMetricsSummaryParams

	// ------------- Optional query parameter "inactive_days" -------------
	if paramValue := c.Query("inactive_days"); paramValue != "" {

		var value int
		err = runtime.BindStyledParameterWithOptions("form", "inactive_days", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter inactive_days: %w", err).Error())
		}
		params.InactiveDays = &value

	}
	// ------------- Optional query parameter "organization" -------------
	if paramValue := c.Query("organization"); paramValue != "" {

		var value Organization
		err = runtime.BindStyledParameterWithOptions("form", "organization", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter organization: %w", err).Error())
		}
		params.Organization = &value

	}
	// ------------- Optional query parameter "project" -------------
	if paramValue := c.Query("project"); paramValue != "" {

		var value Project
		err = runtime.BindStyledParameterWithOptions("form", "project", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter project: %w", err).Error())
		}
		params.Project = &value

	}

	return siw.Handler.GetMetricsSummary(c, params)
}

// GetTransferBreakdown operation middleware
func (siw *ServerInterfaceWrapper) GetTransferBreakdown(c fiber.Ctx) error {
	var err error
	var params GetTransferBreakdownParams

	// ------------- Optional query parameter "organization" -------------
	if paramValue := c.Query("organization"); paramValue != "" {

		var value Organization
		err = runtime.BindStyledParameterWithOptions("form", "organization", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter organization: %w", err).Error())
		}
		params.Organization = &value

	}
	// ------------- Optional query parameter "project" -------------
	if paramValue := c.Query("project"); paramValue != "" {

		var value Project
		err = runtime.BindStyledParameterWithOptions("form", "project", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter project: %w", err).Error())
		}
		params.Project = &value

	}
	// ------------- Optional query parameter "direction" -------------
	if paramValue := c.Query("direction"); paramValue != "" {

		var value Direction
		err = runtime.BindStyledParameterWithOptions("form", "direction", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter direction: %w", err).Error())
		}
		params.Direction = &value

	}
	// ------------- Optional query parameter "reconciliation_status" -------------
	if paramValue := c.Query("reconciliation_status"); paramValue != "" {

		var value ReconciliationStatus
		err = runtime.BindStyledParameterWithOptions("form", "reconciliation_status", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter reconciliation_status: %w", err).Error())
		}
		params.ReconciliationStatus = &value

	}
	// ------------- Optional query parameter "from" -------------
	if paramValue := c.Query("from"); paramValue != "" {

		var value From
		err = runtime.BindStyledParameterWithOptions("form", "from", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter from: %w", err).Error())
		}
		params.From = &value

	}
	// ------------- Optional query parameter "to" -------------
	if paramValue := c.Query("to"); paramValue != "" {

		var value To
		err = runtime.BindStyledParameterWithOptions("form", "to", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter to: %w", err).Error())
		}
		params.To = &value

	}
	// ------------- Optional query parameter "provider" -------------
	if paramValue := c.Query("provider"); paramValue != "" {

		var value Provider
		err = runtime.BindStyledParameterWithOptions("form", "provider", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter provider: %w", err).Error())
		}
		params.Provider = &value

	}
	// ------------- Optional query parameter "bucket" -------------
	if paramValue := c.Query("bucket"); paramValue != "" {

		var value Bucket
		err = runtime.BindStyledParameterWithOptions("form", "bucket", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter bucket: %w", err).Error())
		}
		params.Bucket = &value

	}
	// ------------- Optional query parameter "sha256" -------------
	if paramValue := c.Query("sha256"); paramValue != "" {

		var value SHA256
		err = runtime.BindStyledParameterWithOptions("form", "sha256", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter sha256: %w", err).Error())
		}
		params.Sha256 = &value

	}
	// ------------- Optional query parameter "user" -------------
	if paramValue := c.Query("user"); paramValue != "" {

		var value User
		err = runtime.BindStyledParameterWithOptions("form", "user", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter user: %w", err).Error())
		}
		params.User = &value

	}
	// ------------- Optional query parameter "allow_stale" -------------
	if paramValue := c.Query("allow_stale"); paramValue != "" {

		var value AllowStale
		err = runtime.BindStyledParameterWithOptions("form", "allow_stale", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter allow_stale: %w", err).Error())
		}
		params.AllowStale = &value

	}
	// ------------- Optional query parameter "group_by" -------------
	if paramValue := c.Query("group_by"); paramValue != "" {

		var value GetTransferBreakdownParamsGroupBy
		err = runtime.BindStyledParameterWithOptions("form", "group_by", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter group_by: %w", err).Error())
		}
		params.GroupBy = &value

	}

	return siw.Handler.GetTransferBreakdown(c, params)
}

// GetTransferSummary operation middleware
func (siw *ServerInterfaceWrapper) GetTransferSummary(c fiber.Ctx) error {
	var err error
	var params GetTransferSummaryParams

	// ------------- Optional query parameter "organization" -------------
	if paramValue := c.Query("organization"); paramValue != "" {

		var value Organization
		err = runtime.BindStyledParameterWithOptions("form", "organization", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter organization: %w", err).Error())
		}
		params.Organization = &value

	}
	// ------------- Optional query parameter "project" -------------
	if paramValue := c.Query("project"); paramValue != "" {

		var value Project
		err = runtime.BindStyledParameterWithOptions("form", "project", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter project: %w", err).Error())
		}
		params.Project = &value

	}
	// ------------- Optional query parameter "direction" -------------
	if paramValue := c.Query("direction"); paramValue != "" {

		var value Direction
		err = runtime.BindStyledParameterWithOptions("form", "direction", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter direction: %w", err).Error())
		}
		params.Direction = &value

	}
	// ------------- Optional query parameter "reconciliation_status" -------------
	if paramValue := c.Query("reconciliation_status"); paramValue != "" {

		var value ReconciliationStatus
		err = runtime.BindStyledParameterWithOptions("form", "reconciliation_status", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter reconciliation_status: %w", err).Error())
		}
		params.ReconciliationStatus = &value

	}
	// ------------- Optional query parameter "from" -------------
	if paramValue := c.Query("from"); paramValue != "" {

		var value From
		err = runtime.BindStyledParameterWithOptions("form", "from", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter from: %w", err).Error())
		}
		params.From = &value

	}
	// ------------- Optional query parameter "to" -------------
	if paramValue := c.Query("to"); paramValue != "" {

		var value To
		err = runtime.BindStyledParameterWithOptions("form", "to", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter to: %w", err).Error())
		}
		params.To = &value

	}
	// ------------- Optional query parameter "provider" -------------
	if paramValue := c.Query("provider"); paramValue != "" {

		var value Provider
		err = runtime.BindStyledParameterWithOptions("form", "provider", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter provider: %w", err).Error())
		}
		params.Provider = &value

	}
	// ------------- Optional query parameter "bucket" -------------
	if paramValue := c.Query("bucket"); paramValue != "" {

		var value Bucket
		err = runtime.BindStyledParameterWithOptions("form", "bucket", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter bucket: %w", err).Error())
		}
		params.Bucket = &value

	}
	// ------------- Optional query parameter "sha256" -------------
	if paramValue := c.Query("sha256"); paramValue != "" {

		var value SHA256
		err = runtime.BindStyledParameterWithOptions("form", "sha256", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter sha256: %w", err).Error())
		}
		params.Sha256 = &value

	}
	// ------------- Optional query parameter "user" -------------
	if paramValue := c.Query("user"); paramValue != "" {

		var value User
		err = runtime.BindStyledParameterWithOptions("form", "user", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter user: %w", err).Error())
		}
		params.User = &value

	}
	// ------------- Optional query parameter "allow_stale" -------------
	if paramValue := c.Query("allow_stale"); paramValue != "" {

		var value AllowStale
		err = runtime.BindStyledParameterWithOptions("form", "allow_stale", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter allow_stale: %w", err).Error())
		}
		params.AllowStale = &value

	}

	return siw.Handler.GetTransferSummary(c, params)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/index/v1/metrics/files", wrapper.ListMetricsFiles)

	router.Post(options.BaseURL+"/index/v1/metrics/files/bulk", wrapper.BulkMetricsFiles)

	router.Get(options.BaseURL+"/index/v1/metrics/files/:object_id", wrapper.GetMetricsFile)

	router.Post(options.BaseURL+"/index/v1/metrics/provider-transfer-events", wrapper.RecordProviderTransferEvents)

	router.Get(options.BaseURL+"/index/v1/metrics/summary", wrapper.GetMetricsSummary)

	router.Get(options.BaseURL+"/index/v1/metrics/transfers/breakdown", wrapper.GetTransferBreakdown)

	router.Get(options.BaseURL+"/index/v1/metrics/transfers/summary", wrapper.GetTransferSummary)

}

type ListMetricsFilesRequestObject struct {
	Params ListMetricsFilesParams
}

type ListMetricsFilesResponseObject interface {
	VisitListMetricsFilesResponse(ctx fiber.Ctx) error
}

type ListMetricsFiles200JSONResponse MetricsListResponse

func (response ListMetricsFiles200JSONResponse) VisitListMetricsFilesResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type ListMetricsFiles400JSONResponse APIError

func (response ListMetricsFiles400JSONResponse) VisitListMetricsFilesResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type ListMetricsFiles401JSONResponse APIError

func (response ListMetricsFiles401JSONResponse) VisitListMetricsFilesResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type ListMetricsFiles403JSONResponse APIError

func (response ListMetricsFiles403JSONResponse) VisitListMetricsFilesResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type ListMetricsFiles500JSONResponse APIError

func (response ListMetricsFiles500JSONResponse) VisitListMetricsFilesResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type BulkMetricsFilesRequestObject struct {
	Params BulkMetricsFilesParams
	Body   *BulkMetricsFilesJSONRequestBody
}

type BulkMetricsFilesResponseObject interface {
	VisitBulkMetricsFilesResponse(ctx fiber.Ctx) error
}

type BulkMetricsFiles200JSONResponse MetricsListResponse

func (response BulkMetricsFiles200JSONResponse) VisitBulkMetricsFilesResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type BulkMetricsFiles400JSONResponse APIError

func (response BulkMetricsFiles400JSONResponse) VisitBulkMetricsFilesResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type BulkMetricsFiles401JSONResponse APIError

func (response BulkMetricsFiles401JSONResponse) VisitBulkMetricsFilesResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type BulkMetricsFiles403JSONResponse APIError

func (response BulkMetricsFiles403JSONResponse) VisitBulkMetricsFilesResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type BulkMetricsFiles500JSONResponse APIError

func (response BulkMetricsFiles500JSONResponse) VisitBulkMetricsFilesResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetMetricsFileRequestObject struct {
	ObjectId string `json:"object_id"`
	Params   GetMetricsFileParams
}

type GetMetricsFileResponseObject interface {
	VisitGetMetricsFileResponse(ctx fiber.Ctx) error
}

type GetMetricsFile200JSONResponse FileUsage

func (response GetMetricsFile200JSONResponse) VisitGetMetricsFileResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetMetricsFile400JSONResponse APIError

func (response GetMetricsFile400JSONResponse) VisitGetMetricsFileResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type GetMetricsFile401JSONResponse APIError

func (response GetMetricsFile401JSONResponse) VisitGetMetricsFileResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type GetMetricsFile403JSONResponse APIError

func (response GetMetricsFile403JSONResponse) VisitGetMetricsFileResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type GetMetricsFile404JSONResponse APIError

func (response GetMetricsFile404JSONResponse) VisitGetMetricsFileResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type GetMetricsFile500JSONResponse APIError

func (response GetMetricsFile500JSONResponse) VisitGetMetricsFileResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type RecordProviderTransferEventsRequestObject struct {
	Params RecordProviderTransferEventsParams
	Body   *RecordProviderTransferEventsJSONRequestBody
}

type RecordProviderTransferEventsResponseObject interface {
	VisitRecordProviderTransferEventsResponse(ctx fiber.Ctx) error
}

type RecordProviderTransferEvents201JSONResponse TransferEventsRecordedResponse

func (response RecordProviderTransferEvents201JSONResponse) VisitRecordProviderTransferEventsResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(201)

	return ctx.JSON(&response)
}

type RecordProviderTransferEvents400JSONResponse APIError

func (response RecordProviderTransferEvents400JSONResponse) VisitRecordProviderTransferEventsResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type RecordProviderTransferEvents401JSONResponse APIError

func (response RecordProviderTransferEvents401JSONResponse) VisitRecordProviderTransferEventsResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type RecordProviderTransferEvents403JSONResponse APIError

func (response RecordProviderTransferEvents403JSONResponse) VisitRecordProviderTransferEventsResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type RecordProviderTransferEvents500JSONResponse APIError

func (response RecordProviderTransferEvents500JSONResponse) VisitRecordProviderTransferEventsResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetMetricsSummaryRequestObject struct {
	Params GetMetricsSummaryParams
}

type GetMetricsSummaryResponseObject interface {
	VisitGetMetricsSummaryResponse(ctx fiber.Ctx) error
}

type GetMetricsSummary200JSONResponse FileUsageSummary

func (response GetMetricsSummary200JSONResponse) VisitGetMetricsSummaryResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetMetricsSummary400JSONResponse APIError

func (response GetMetricsSummary400JSONResponse) VisitGetMetricsSummaryResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type GetMetricsSummary401JSONResponse APIError

func (response GetMetricsSummary401JSONResponse) VisitGetMetricsSummaryResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type GetMetricsSummary403JSONResponse APIError

func (response GetMetricsSummary403JSONResponse) VisitGetMetricsSummaryResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type GetMetricsSummary500JSONResponse APIError

func (response GetMetricsSummary500JSONResponse) VisitGetMetricsSummaryResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetTransferBreakdownRequestObject struct {
	Params GetTransferBreakdownParams
}

type GetTransferBreakdownResponseObject interface {
	VisitGetTransferBreakdownResponse(ctx fiber.Ctx) error
}

type GetTransferBreakdown200JSONResponse TransferBreakdownResponse

func (response GetTransferBreakdown200JSONResponse) VisitGetTransferBreakdownResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetTransferBreakdown400JSONResponse APIError

func (response GetTransferBreakdown400JSONResponse) VisitGetTransferBreakdownResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type GetTransferBreakdown401JSONResponse APIError

func (response GetTransferBreakdown401JSONResponse) VisitGetTransferBreakdownResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type GetTransferBreakdown403JSONResponse APIError

func (response GetTransferBreakdown403JSONResponse) VisitGetTransferBreakdownResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type GetTransferBreakdown500JSONResponse APIError

func (response GetTransferBreakdown500JSONResponse) VisitGetTransferBreakdownResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetTransferSummaryRequestObject struct {
	Params GetTransferSummaryParams
}

type GetTransferSummaryResponseObject interface {
	VisitGetTransferSummaryResponse(ctx fiber.Ctx) error
}

type GetTransferSummary200JSONResponse TransferAttributionSummary

func (response GetTransferSummary200JSONResponse) VisitGetTransferSummaryResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetTransferSummary400JSONResponse APIError

func (response GetTransferSummary400JSONResponse) VisitGetTransferSummaryResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type GetTransferSummary401JSONResponse APIError

func (response GetTransferSummary401JSONResponse) VisitGetTransferSummaryResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type GetTransferSummary403JSONResponse APIError

func (response GetTransferSummary403JSONResponse) VisitGetTransferSummaryResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type GetTransferSummary500JSONResponse APIError

func (response GetTransferSummary500JSONResponse) VisitGetTransferSummaryResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /index/v1/metrics/files)
	ListMetricsFiles(ctx context.Context, request ListMetricsFilesRequestObject) (ListMetricsFilesResponseObject, error)

	// (POST /index/v1/metrics/files/bulk)
	BulkMetricsFiles(ctx context.Context, request BulkMetricsFilesRequestObject) (BulkMetricsFilesResponseObject, error)

	// (GET /index/v1/metrics/files/{object_id})
	GetMetricsFile(ctx context.Context, request GetMetricsFileRequestObject) (GetMetricsFileResponseObject, error)
	// Record provider-observed transfer events
	// (POST /index/v1/metrics/provider-transfer-events)
	RecordProviderTransferEvents(ctx context.Context, request RecordProviderTransferEventsRequestObject) (RecordProviderTransferEventsResponseObject, error)

	// (GET /index/v1/metrics/summary)
	GetMetricsSummary(ctx context.Context, request GetMetricsSummaryRequestObject) (GetMetricsSummaryResponseObject, error)
	// Group transfer attribution events
	// (GET /index/v1/metrics/transfers/breakdown)
	GetTransferBreakdown(ctx context.Context, request GetTransferBreakdownRequestObject) (GetTransferBreakdownResponseObject, error)
	// Summarize transfer attribution events
	// (GET /index/v1/metrics/transfers/summary)
	GetTransferSummary(ctx context.Context, request GetTransferSummaryRequestObject) (GetTransferSummaryResponseObject, error)
}

type StrictHandlerFunc func(ctx fiber.Ctx, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListMetricsFiles operation middleware
func (sh *strictHandler) ListMetricsFiles(ctx fiber.Ctx, params ListMetricsFilesParams) error {
	var request ListMetricsFilesRequestObject

	request.Params = params

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.ListMetricsFiles(ctx.Context(), request.(ListMetricsFilesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListMetricsFiles")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(ListMetricsFilesResponseObject); ok {
		if err := validResponse.VisitListMetricsFilesResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// BulkMetricsFiles operation middleware
func (sh *strictHandler) BulkMetricsFiles(ctx fiber.Ctx, params BulkMetricsFilesParams) error {
	var request BulkMetricsFilesRequestObject

	request.Params = params

	var body BulkMetricsFilesJSONRequestBody
	if err := ctx.Bind().Body(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.BulkMetricsFiles(ctx.Context(), request.(BulkMetricsFilesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BulkMetricsFiles")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(BulkMetricsFilesResponseObject); ok {
		if err := validResponse.VisitBulkMetricsFilesResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMetricsFile operation middleware
func (sh *strictHandler) GetMetricsFile(ctx fiber.Ctx, objectId string, params GetMetricsFileParams) error {
	var request GetMetricsFileRequestObject

	request.ObjectId = objectId
	request.Params = params

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetMetricsFile(ctx.Context(), request.(GetMetricsFileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMetricsFile")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetMetricsFileResponseObject); ok {
		if err := validResponse.VisitGetMetricsFileResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RecordProviderTransferEvents operation middleware
func (sh *strictHandler) RecordProviderTransferEvents(ctx fiber.Ctx, params RecordProviderTransferEventsParams) error {
	var request RecordProviderTransferEventsRequestObject

	request.Params = params

	var body RecordProviderTransferEventsJSONRequestBody
	if err := ctx.Bind().Body(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.RecordProviderTransferEvents(ctx.Context(), request.(RecordProviderTransferEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RecordProviderTransferEvents")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(RecordProviderTransferEventsResponseObject); ok {
		if err := validResponse.VisitRecordProviderTransferEventsResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMetricsSummary operation middleware
func (sh *strictHandler) GetMetricsSummary(ctx fiber.Ctx, params GetMetricsSummaryParams) error {
	var request GetMetricsSummaryRequestObject

	request.Params = params

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetMetricsSummary(ctx.Context(), request.(GetMetricsSummaryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMetricsSummary")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetMetricsSummaryResponseObject); ok {
		if err := validResponse.VisitGetMetricsSummaryResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetTransferBreakdown operation middleware
func (sh *strictHandler) GetTransferBreakdown(ctx fiber.Ctx, params GetTransferBreakdownParams) error {
	var request GetTransferBreakdownRequestObject

	request.Params = params

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetTransferBreakdown(ctx.Context(), request.(GetTransferBreakdownRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTransferBreakdown")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetTransferBreakdownResponseObject); ok {
		if err := validResponse.VisitGetTransferBreakdownResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetTransferSummary operation middleware
func (sh *strictHandler) GetTransferSummary(ctx fiber.Ctx, params GetTransferSummaryParams) error {
	var request GetTransferSummaryRequestObject

	request.Params = params

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetTransferSummary(ctx.Context(), request.(GetTransferSummaryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTransferSummary")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetTransferSummaryResponseObject); ok {
		if err := validResponse.VisitGetTransferSummaryResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
