// Package bucketapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package bucketapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	externalRef0 "github.com/calypr/syfon/apigen/errorapi"
	"github.com/gofiber/fiber/v3"
	"github.com/oapi-codegen/runtime"
)

// APIError A stable Syfon API error.
type APIError = externalRef0.APIError

// AddBucketScopeRequest defines model for AddBucketScopeRequest.
type AddBucketScopeRequest struct {
	Organization string `json:"organization"`

	// Path Optional s3://bucket/prefix path override
	Path      *string `json:"path,omitempty"`
	ProjectId string  `json:"project_id"`
}

// BucketMetadata defines model for BucketMetadata.
type BucketMetadata struct {
	Bucket      *string   `json:"bucket,omitempty"`
	EndpointUrl *string   `json:"endpoint_url,omitempty"`
	Programs    *[]string `json:"programs,omitempty"`
	Provider    *string   `json:"provider,omitempty"`
	Region      *string   `json:"region,omitempty"`
}

// BucketScopeResponse defines model for BucketScopeResponse.
type BucketScopeResponse struct {
	Organization string `json:"organization"`

	// Path Scope path prefix
	Path      *string `json:"path,omitempty"`
	ProjectId string  `json:"project_id"`
}

// BucketsResponse defines model for BucketsResponse.
type BucketsResponse struct {
	S3BUCKETS map[string]BucketMetadata `json:"S3_BUCKETS"`
}

// DeleteProjectDataResponse defines model for DeleteProjectDataResponse.
type DeleteProjectDataResponse struct {
	DeletedBucketScopes int    `json:"deleted_bucket_scopes"`
	DeletedObjects      int    `json:"deleted_objects"`
	Organization        string `json:"organization"`
	ProjectId           string `json:"project_id"`
}

// PutBucketRequest defines model for PutBucketRequest.
type PutBucketRequest struct {
	AccessKey    *string `json:"access_key,omitempty"`
	Bucket       string  `json:"bucket"`
	Endpoint     *string `json:"endpoint,omitempty"`
	Organization string  `json:"organization"`

	// Path Optional s3://bucket/prefix path override
	Path      *string `json:"path,omitempty"`
	ProjectId string  `json:"project_id"`

	// Provider Storage backend provider (s3|gcs|azure|file). Defaults to s3.
	Provider  *string `json:"provider,omitempty"`
	Region    *string `json:"region,omitempty"`
	SecretKey *string `json:"secret_key,omitempty"`
}

// DeleteBucketScopeParams defines parameters for DeleteBucketScope.
type DeleteBucketScopeParams struct {
	Organization string  `form:"organization" json:"organization"`
	Path         string  `form:"path" json:"path"`
	ProjectId    *string `form:"project_id,omitempty" json:"project_id,omitempty"`
}

// PutBucketJSONRequestBody defines body for PutBucket for application/json ContentType.
type PutBucketJSONRequestBody = PutBucketRequest

// AddBucketScopeJSONRequestBody defines body for AddBucketScope for application/json ContentType.
type AddBucketScopeJSONRequestBody = AddBucketScopeRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListBuckets request
	ListBuckets(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutBucketWithBody request with any body
	PutBucketWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutBucket(ctx context.Context, body PutBucketJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteBucket request
	DeleteBucket(ctx context.Context, bucket string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteBucketScope request
	DeleteBucketScope(ctx context.Context, bucket string, params *DeleteBucketScopeParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListBucketScopes request
	ListBucketScopes(ctx context.Context, bucket string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AddBucketScopeWithBody request with any body
	AddBucketScopeWithBody(ctx context.Context, bucket string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AddBucketScope(ctx context.Context, bucket string, body AddBucketScopeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteProjectData request
	DeleteProjectData(ctx context.Context, organization string, projectId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListBuckets(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListBucketsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutBucketWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutBucketRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutBucket(ctx context.Context, body PutBucketJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutBucketRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteBucket(ctx context.Context, bucket string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteBucketRequest(c.Server, bucket)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteBucketScope(ctx context.Context, bucket string, params *DeleteBucketScopeParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteBucketScopeRequest(c.Server, bucket, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListBucketScopes(ctx context.Context, bucket string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListBucketScopesRequest(c.Server, bucket)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddBucketScopeWithBody(ctx context.Context, bucket string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddBucketScopeRequestWithBody(c.Server, bucket, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddBucketScope(ctx context.Context, bucket string, body AddBucketScopeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddBucketScopeRequest(c.Server, bucket, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteProjectData(ctx context.Context, organization string, projectId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteProjectDataRequest(c.Server, organization, projectId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListBucketsRequest generates requests for ListBuckets
func NewListBucketsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/data/buckets")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutBucketRequest calls the generic PutBucket builder with application/json body
func NewPutBucketRequest(server string, body PutBucketJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutBucketRequestWithBody(server, "application/json", bodyReader)
}

// NewPutBucketRequestWithBody generates requests for PutBucket with any type of body
func NewPutBucketRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/data/buckets")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteBucketRequest generates requests for DeleteBucket
func NewDeleteBucketRequest(server string, bucket string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "bucket", runtime.ParamLocationPath, bucket)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/data/buckets/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteBucketScopeRequest generates requests for DeleteBucketScope
func NewDeleteBucketScopeRequest(server string, bucket string, params *DeleteBucketScopeParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "bucket", runtime.ParamLocationPath, bucket)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/data/buckets/%s/scopes", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "organization", runtime.ParamLocationQuery, params.Organization); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "path", runtime.ParamLocationQuery, params.Path); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.ProjectId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "project_id", runtime.ParamLocationQuery, *params.ProjectId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListBucketScopesRequest generates requests for ListBucketScopes
func NewListBucketScopesRequest(server string, bucket string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "bucket", runtime.ParamLocationPath, bucket)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/data/buckets/%s/scopes", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAddBucketScopeRequest calls the generic AddBucketScope builder with application/json body
func NewAddBucketScopeRequest(server string, bucket string, body AddBucketScopeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAddBucketScopeRequestWithBody(server, bucket, "application/json", bodyReader)
}

// NewAddBucketScopeRequestWithBody generates requests for AddBucketScope with any type of body
func NewAddBucketScopeRequestWithBody(server string, bucket string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "bucket", runtime.ParamLocationPath, bucket)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/data/buckets/%s/scopes", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteProjectDataRequest generates requests for DeleteProjectData
func NewDeleteProjectDataRequest(server string, organization string, projectId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organization", runtime.ParamLocationPath, organization)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "project_id", runtime.ParamLocationPath, projectId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/data/projects/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListBucketsWithResponse request
	ListBucketsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListBucketsResp, error)

	// PutBucketWithBodyWithResponse request with any body
	PutBucketWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutBucketResp, error)

	PutBucketWithResponse(ctx context.Context, body PutBucketJSONRequestBody, reqEditors ...RequestEditorFn) (*PutBucketResp, error)

	// DeleteBucketWithResponse request
	DeleteBucketWithResponse(ctx context.Context, bucket string, reqEditors ...RequestEditorFn) (*DeleteBucketResp, error)

	// DeleteBucketScopeWithResponse request
	DeleteBucketScopeWithResponse(ctx context.Context, bucket string, params *DeleteBucketScopeParams, reqEditors ...RequestEditorFn) (*DeleteBucketScopeResp, error)

	// ListBucketScopesWithResponse request
	ListBucketScopesWithResponse(ctx context.Context, bucket string, reqEditors ...RequestEditorFn) (*ListBucketScopesResp, error)

	// AddBucketScopeWithBodyWithResponse request with any body
	AddBucketScopeWithBodyWithResponse(ctx context.Context, bucket string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddBucketScopeResp, error)

	AddBucketScopeWithResponse(ctx context.Context, bucket string, body AddBucketScopeJSONRequestBody, reqEditors ...RequestEditorFn) (*AddBucketScopeResp, error)

	// DeleteProjectDataWithResponse request
	DeleteProjectDataWithResponse(ctx context.Context, organization string, projectId string, reqEditors ...RequestEditorFn) (*DeleteProjectDataResp, error)
}

type ListBucketsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BucketsResponse
	JSON401      *APIError
	JSON403      *APIError
	JSON500      *APIError
}

// Status returns HTTPResponse.Status
func (r ListBucketsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListBucketsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutBucketResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *APIError
	JSON401      *APIError
	JSON403      *APIError
	JSON409      *APIError
	JSON500      *APIError
}

// Status returns HTTPResponse.Status
func (r PutBucketResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutBucketResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteBucketResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *APIError
	JSON401      *APIError
	JSON403      *APIError
	JSON404      *APIError
	JSON500      *APIError
}

// Status returns HTTPResponse.Status
func (r DeleteBucketResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteBucketResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteBucketScopeResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *APIError
	JSON401      *APIError
	JSON403      *APIError
	JSON404      *APIError
	JSON500      *APIError
}

// Status returns HTTPResponse.Status
func (r DeleteBucketScopeResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteBucketScopeResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListBucketScopesResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]BucketScopeResponse
	JSON401      *APIError
	JSON403      *APIError
	JSON404      *APIError
	JSON500      *APIError
}

// Status returns HTTPResponse.Status
func (r ListBucketScopesResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListBucketScopesResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AddBucketScopeResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *APIError
	JSON401      *APIError
	JSON403      *APIError
	JSON404      *APIError
	JSON409      *APIError
	JSON500      *APIError
}

// Status returns HTTPResponse.Status
func (r AddBucketScopeResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddBucketScopeResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteProjectDataResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DeleteProjectDataResponse
	JSON400      *APIError
	JSON401      *APIError
	JSON403      *APIError
	JSON500      *APIError
}

// Status returns HTTPResponse.Status
func (r DeleteProjectDataResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteProjectDataResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListBucketsWithResponse request returning *ListBucketsResp
func (c *ClientWithResponses) ListBucketsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListBucketsResp, error) {
	rsp, err := c.ListBuckets(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListBucketsResp(rsp)
}

// PutBucketWithBodyWithResponse request with arbitrary body returning *PutBucketResp
func (c *ClientWithResponses) PutBucketWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutBucketResp, error) {
	rsp, err := c.PutBucketWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutBucketResp(rsp)
}

func (c *ClientWithResponses) PutBucketWithResponse(ctx context.Context, body PutBucketJSONRequestBody, reqEditors ...RequestEditorFn) (*PutBucketResp, error) {
	rsp, err := c.PutBucket(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutBucketResp(rsp)
}

// DeleteBucketWithResponse request returning *DeleteBucketResp
func (c *ClientWithResponses) DeleteBucketWithResponse(ctx context.Context, bucket string, reqEditors ...RequestEditorFn) (*DeleteBucketResp, error) {
	rsp, err := c.DeleteBucket(ctx, bucket, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteBucketResp(rsp)
}

// DeleteBucketScopeWithResponse request returning *DeleteBucketScopeResp
func (c *ClientWithResponses) DeleteBucketScopeWithResponse(ctx context.Context, bucket string, params *DeleteBucketScopeParams, reqEditors ...RequestEditorFn) (*DeleteBucketScopeResp, error) {
	rsp, err := c.DeleteBucketScope(ctx, bucket, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteBucketScopeResp(rsp)
}

// ListBucketScopesWithResponse request returning *ListBucketScopesResp
func (c *ClientWithResponses) ListBucketScopesWithResponse(ctx context.Context, bucket string, reqEditors ...RequestEditorFn) (*ListBucketScopesResp, error) {
	rsp, err := c.ListBucketScopes(ctx, bucket, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListBucketScopesResp(rsp)
}

// AddBucketScopeWithBodyWithResponse request with arbitrary body returning *AddBucketScopeResp
func (c *ClientWithResponses) AddBucketScopeWithBodyWithResponse(ctx context.Context, bucket string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddBucketScopeResp, error) {
	rsp, err := c.AddBucketScopeWithBody(ctx, bucket, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddBucketScopeResp(rsp)
}

func (c *ClientWithResponses) AddBucketScopeWithResponse(ctx context.Context, bucket string, body AddBucketScopeJSONRequestBody, reqEditors ...RequestEditorFn) (*AddBucketScopeResp, error) {
	rsp, err := c.AddBucketScope(ctx, bucket, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddBucketScopeResp(rsp)
}

// DeleteProjectDataWithResponse request returning *DeleteProjectDataResp
func (c *ClientWithResponses) DeleteProjectDataWithResponse(ctx context.Context, organization string, projectId string, reqEditors ...RequestEditorFn) (*DeleteProjectDataResp, error) {
	rsp, err := c.DeleteProjectData(ctx, organization, projectId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteProjectDataResp(rsp)
}

// ParseListBucketsResp parses an HTTP response from a ListBucketsWithResponse call
func ParseListBucketsResp(rsp *http.Response) (*ListBucketsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListBucketsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BucketsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePutBucketResp parses an HTTP response from a PutBucketWithResponse call
func ParsePutBucketResp(rsp *http.Response) (*PutBucketResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutBucketResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteBucketResp parses an HTTP response from a DeleteBucketWithResponse call
func ParseDeleteBucketResp(rsp *http.Response) (*DeleteBucketResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteBucketResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteBucketScopeResp parses an HTTP response from a DeleteBucketScopeWithResponse call
func ParseDeleteBucketScopeResp(rsp *http.Response) (*DeleteBucketScopeResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteBucketScopeResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseListBucketScopesResp parses an HTTP response from a ListBucketScopesWithResponse call
func ParseListBucketScopesResp(rsp *http.Response) (*ListBucketScopesResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListBucketScopesResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []BucketScopeResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseAddBucketScopeResp parses an HTTP response from a AddBucketScopeWithResponse call
func ParseAddBucketScopeResp(rsp *http.Response) (*AddBucketScopeResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddBucketScopeResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteProjectDataResp parses an HTTP response from a DeleteProjectDataWithResponse call
func ParseDeleteProjectDataResp(rsp *http.Response) (*DeleteProjectDataResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteProjectDataResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DeleteProjectDataResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List configured bucket credentials and org/project assignments
	// (GET /data/buckets)
	ListBuckets(c fiber.Ctx) error
	// Upsert bucket credential and claim org/project scope
	// (PUT /data/buckets)
	PutBucket(c fiber.Ctx) error
	// Delete bucket credential
	// (DELETE /data/buckets/{bucket})
	DeleteBucket(c fiber.Ctx, bucket string) error
	// Remove a specific scope from an existing bucket
	// (DELETE /data/buckets/{bucket}/scopes)
	DeleteBucketScope(c fiber.Ctx, bucket string, params DeleteBucketScopeParams) error
	// List org/project scopes for a bucket
	// (GET /data/buckets/{bucket}/scopes)
	ListBucketScopes(c fiber.Ctx, bucket string) error
	// Add an org/project scope to an existing bucket
	// (POST /data/buckets/{bucket}/scopes)
	AddBucketScope(c fiber.Ctx, bucket string) error
	// Delete Syfon records and bucket scopes for a project
	// (DELETE /data/projects/{organization}/{project_id})
	DeleteProjectData(c fiber.Ctx, organization string, projectId string) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// ListBuckets operation middleware
func (siw *ServerInterfaceWrapper) ListBuckets(c fiber.Ctx) error {

	return siw.Handler.ListBuckets(c)
}

// PutBucket operation middleware
func (siw *ServerInterfaceWrapper) PutBucket(c fiber.Ctx) error {

	return siw.Handler.PutBucket(c)
}

// DeleteBucket operation middleware
func (siw *ServerInterfaceWrapper) DeleteBucket(c fiber.Ctx) error {
	var err error

	// ------------- Path parameter "bucket" -------------
	var bucket string

	err = runtime.BindStyledParameterWithOptions("simple", "bucket", c.Params("bucket"), &bucket, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter bucket: %w", err).Error())
	}

	return siw.Handler.DeleteBucket(c, bucket)
}

// DeleteBucketScope operation middleware
func (siw *ServerInterfaceWrapper) DeleteBucketScope(c fiber.Ctx) error {
	var err error
	var params DeleteBucketScopeParams

	// ------------- Path parameter "bucket" -------------
	var bucket string

	err = runtime.BindStyledParameterWithOptions("simple", "bucket", c.Params("bucket"), &bucket, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter bucket: %w", err).Error())
	}

	// ------------- Required query parameter "organization" -------------
	if paramValue := c.Query("organization"); paramValue != "" {

		var value string
		err = runtime.BindStyledParameterWithOptions("form", "organization", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: true})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter organization: %w", err).Error())
		}
		params.Organization = value

	} else {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Query argument organization is required, but not found").Error())
	}
	// ------------- Required query parameter "path" -------------
	if paramValue := c.Query("path"); paramValue != "" {

		var value string
		err = runtime.BindStyledParameterWithOptions("form", "path", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: true})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter path: %w", err).Error())
		}
		params.Path = value

	} else {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Query argument path is required, but not found").Error())
	}
	// ------------- Optional query parameter "project_id" -------------
	if paramValue := c.Query("project_id"); paramValue != "" {

		var value string
		err = runtime.BindStyledParameterWithOptions("form", "project_id", paramValue, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter project_id: %w", err).Error())
		}
		params.ProjectId = &value

	}

	return siw.Handler.DeleteBucketScope(c, bucket, params)
}

// ListBucketScopes operation middleware
func (siw *ServerInterfaceWrapper) ListBucketScopes(c fiber.Ctx) error {
	var err error

	// ------------- Path parameter "bucket" -------------
	var bucket string

	err = runtime.BindStyledParameterWithOptions("simple", "bucket", c.Params("bucket"), &bucket, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter bucket: %w", err).Error())
	}

	return siw.Handler.ListBucketScopes(c, bucket)
}

// AddBucketScope operation middleware
func (siw *ServerInterfaceWrapper) AddBucketScope(c fiber.Ctx) error {
	var err error

	// ------------- Path parameter "bucket" -------------
	var bucket string

	err = runtime.BindStyledParameterWithOptions("simple", "bucket", c.Params("bucket"), &bucket, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter bucket: %w", err).Error())
	}

	return siw.Handler.AddBucketScope(c, bucket)
}

// DeleteProjectData operation middleware
func (siw *ServerInterfaceWrapper) DeleteProjectData(c fiber.Ctx) error {
	var err error

	// ------------- Path parameter "organization" -------------
	var organization string

	err = runtime.BindStyledParameterWithOptions("simple", "organization", c.Params("organization"), &organization, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter organization: %w", err).Error())
	}

	// ------------- Path parameter "project_id" -------------
	var projectId string

	err = runtime.BindStyledParameterWithOptions("simple", "project_id", c.Params("project_id"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter project_id: %w", err).Error())
	}

	return siw.Handler.DeleteProjectData(c, organization, projectId)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/data/buckets", wrapper.ListBuckets)

	router.Put(options.BaseURL+"/data/buckets", wrapper.PutBucket)

	router.Delete(options.BaseURL+"/data/buckets/:bucket", wrapper.DeleteBucket)

	router.Delete(options.BaseURL+"/data/buckets/:bucket/scopes", wrapper.DeleteBucketScope)

	router.Get(options.BaseURL+"/data/buckets/:bucket/scopes", wrapper.ListBucketScopes)

	router.Post(options.BaseURL+"/data/buckets/:bucket/scopes", wrapper.AddBucketScope)

	router.Delete(options.BaseURL+"/data/projects/:organization/:project_id", wrapper.DeleteProjectData)

}

type ListBucketsRequestObject struct {
}

type ListBucketsResponseObject interface {
	VisitListBucketsResponse(ctx fiber.Ctx) error
}

type ListBuckets200JSONResponse BucketsResponse

func (response ListBuckets200JSONResponse) VisitListBucketsResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type ListBuckets401JSONResponse APIError

func (response ListBuckets401JSONResponse) VisitListBucketsResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type ListBuckets403JSONResponse APIError

func (response ListBuckets403JSONResponse) VisitListBucketsResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type ListBuckets500JSONResponse APIError

func (response ListBuckets500JSONResponse) VisitListBucketsResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type PutBucketRequestObject struct {
	Body *PutBucketJSONRequestBody
}

type PutBucketResponseObject interface {
	VisitPutBucketResponse(ctx fiber.Ctx) error
}

type PutBucket201Response struct {
}

func (response PutBucket201Response) VisitPutBucketResponse(ctx fiber.Ctx) error {
	ctx.Status(201)
	return nil
}

type PutBucket400JSONResponse APIError

func (response PutBucket400JSONResponse) VisitPutBucketResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type PutBucket401JSONResponse APIError

func (response PutBucket401JSONResponse) VisitPutBucketResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type PutBucket403JSONResponse APIError

func (response PutBucket403JSONResponse) VisitPutBucketResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type PutBucket409JSONResponse APIError

func (response PutBucket409JSONResponse) VisitPutBucketResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type PutBucket500JSONResponse APIError

func (response PutBucket500JSONResponse) VisitPutBucketResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type DeleteBucketRequestObject struct {
	Bucket string `json:"bucket"`
}

type DeleteBucketResponseObject interface {
	VisitDeleteBucketResponse(ctx fiber.Ctx) error
}

type DeleteBucket204Response struct {
}

func (response DeleteBucket204Response) VisitDeleteBucketResponse(ctx fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

type DeleteBucket400JSONResponse APIError

func (response DeleteBucket400JSONResponse) VisitDeleteBucketResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type DeleteBucket401JSONResponse APIError

func (response DeleteBucket401JSONResponse) VisitDeleteBucketResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type DeleteBucket403JSONResponse APIError

func (response DeleteBucket403JSONResponse) VisitDeleteBucketResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type DeleteBucket404JSONResponse APIError

func (response DeleteBucket404JSONResponse) VisitDeleteBucketResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type DeleteBucket500JSONResponse APIError

func (response DeleteBucket500JSONResponse) VisitDeleteBucketResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type DeleteBucketScopeRequestObject struct {
	Bucket string `json:"bucket"`
	Params DeleteBucketScopeParams
}

type DeleteBucketScopeResponseObject interface {
	VisitDeleteBucketScopeResponse(ctx fiber.Ctx) error
}

type DeleteBucketScope204Response struct {
}

func (response DeleteBucketScope204Response) VisitDeleteBucketScopeResponse(ctx fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

type DeleteBucketScope400JSONResponse APIError

func (response DeleteBucketScope400JSONResponse) VisitDeleteBucketScopeResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type DeleteBucketScope401JSONResponse APIError

func (response DeleteBucketScope401JSONResponse) VisitDeleteBucketScopeResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type DeleteBucketScope403JSONResponse APIError

func (response DeleteBucketScope403JSONResponse) VisitDeleteBucketScopeResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type DeleteBucketScope404JSONResponse APIError

func (response DeleteBucketScope404JSONResponse) VisitDeleteBucketScopeResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type DeleteBucketScope500JSONResponse APIError

func (response DeleteBucketScope500JSONResponse) VisitDeleteBucketScopeResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type ListBucketScopesRequestObject struct {
	Bucket string `json:"bucket"`
}

type ListBucketScopesResponseObject interface {
	VisitListBucketScopesResponse(ctx fiber.Ctx) error
}

type ListBucketScopes200JSONResponse []BucketScopeResponse

func (response ListBucketScopes200JSONResponse) VisitListBucketScopesResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type ListBucketScopes401JSONResponse APIError

func (response ListBucketScopes401JSONResponse) VisitListBucketScopesResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type ListBucketScopes403JSONResponse APIError

func (response ListBucketScopes403JSONResponse) VisitListBucketScopesResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type ListBucketScopes404JSONResponse APIError

func (response ListBucketScopes404JSONResponse) VisitListBucketScopesResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type ListBucketScopes500JSONResponse APIError

func (response ListBucketScopes500JSONResponse) VisitListBucketScopesResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type AddBucketScopeRequestObject struct {
	Bucket string `json:"bucket"`
	Body   *AddBucketScopeJSONRequestBody
}

type AddBucketScopeResponseObject interface {
	VisitAddBucketScopeResponse(ctx fiber.Ctx) error
}

type AddBucketScope201Response struct {
}

func (response AddBucketScope201Response) VisitAddBucketScopeResponse(ctx fiber.Ctx) error {
	ctx.Status(201)
	return nil
}

type AddBucketScope400JSONResponse APIError

func (response AddBucketScope400JSONResponse) VisitAddBucketScopeResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type AddBucketScope401JSONResponse APIError

func (response AddBucketScope401JSONResponse) VisitAddBucketScopeResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type AddBucketScope403JSONResponse APIError

func (response AddBucketScope403JSONResponse) VisitAddBucketScopeResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type AddBucketScope404JSONResponse APIError

func (response AddBucketScope404JSONResponse) VisitAddBucketScopeResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type AddBucketScope409JSONResponse APIError

func (response AddBucketScope409JSONResponse) VisitAddBucketScopeResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type AddBucketScope500JSONResponse APIError

func (response AddBucketScope500JSONResponse) VisitAddBucketScopeResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type DeleteProjectDataRequestObject struct {
	Organization string `json:"organization"`
	ProjectId    string `json:"project_id"`
}

type DeleteProjectDataResponseObject interface {
	VisitDeleteProjectDataResponse(ctx fiber.Ctx) error
}

type DeleteProjectData200JSONResponse DeleteProjectDataResponse

func (response DeleteProjectData200JSONResponse) VisitDeleteProjectDataResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type DeleteProjectData400JSONResponse APIError

func (response DeleteProjectData400JSONResponse) VisitDeleteProjectDataResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type DeleteProjectData401JSONResponse APIError

func (response DeleteProjectData401JSONResponse) VisitDeleteProjectDataResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type DeleteProjectData403JSONResponse APIError

func (response DeleteProjectData403JSONResponse) VisitDeleteProjectDataResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type DeleteProjectData500JSONResponse APIError

func (response DeleteProjectData500JSONResponse) VisitDeleteProjectDataResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List configured bucket credentials and org/project assignments
	// (GET /data/buckets)
	ListBuckets(ctx context.Context, request ListBucketsRequestObject) (ListBucketsResponseObject, error)
	// Upsert bucket credential and claim org/project scope
	// (PUT /data/buckets)
	PutBucket(ctx context.Context, request PutBucketRequestObject) (PutBucketResponseObject, error)
	// Delete bucket credential
	// (DELETE /data/buckets/{bucket})
	DeleteBucket(ctx context.Context, request DeleteBucketRequestObject) (DeleteBucketResponseObject, error)
	// Remove a specific scope from an existing bucket
	// (DELETE /data/buckets/{bucket}/scopes)
	DeleteBucketScope(ctx context.Context, request DeleteBucketScopeRequestObject) (DeleteBucketScopeResponseObject, error)
	// List org/project scopes for a bucket
	// (GET /data/buckets/{bucket}/scopes)
	ListBucketScopes(ctx context.Context, request ListBucketScopesRequestObject) (ListBucketScopesResponseObject, error)
	// Add an org/project scope to an existing bucket
	// (POST /data/buckets/{bucket}/scopes)
	AddBucketScope(ctx context.Context, request AddBucketScopeRequestObject) (AddBucketScopeResponseObject, error)
	// Delete Syfon records and bucket scopes for a project
	// (DELETE /data/projects/{organization}/{project_id})
	DeleteProjectData(ctx context.Context, request DeleteProjectDataRequestObject) (DeleteProjectDataResponseObject, error)
}

type StrictHandlerFunc func(ctx fiber.Ctx, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListBuckets operation middleware
func (sh *strictHandler) ListBuckets(ctx fiber.Ctx) error {
	var request ListBucketsRequestObject

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.ListBuckets(ctx.Context(), request.(ListBucketsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListBuckets")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(ListBucketsResponseObject); ok {
		if err := validResponse.VisitListBucketsResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PutBucket operation middleware
func (sh *strictHandler) PutBucket(ctx fiber.Ctx) error {
	var request PutBucketRequestObject

	var body PutBucketJSONRequestBody
	if err := ctx.Bind().Body(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.PutBucket(ctx.Context(), request.(PutBucketRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutBucket")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(PutBucketResponseObject); ok {
		if err := validResponse.VisitPutBucketResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteBucket operation middleware
func (sh *strictHandler) DeleteBucket(ctx fiber.Ctx, bucket string) error {
	var request DeleteBucketRequestObject

	request.Bucket = bucket

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteBucket(ctx.Context(), request.(DeleteBucketRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteBucket")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(DeleteBucketResponseObject); ok {
		if err := validResponse.VisitDeleteBucketResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteBucketScope operation middleware
func (sh *strictHandler) DeleteBucketScope(ctx fiber.Ctx, bucket string, params DeleteBucketScopeParams) error {
	var request DeleteBucketScopeRequestObject

	request.Bucket = bucket
	request.Params = params

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteBucketScope(ctx.Context(), request.(DeleteBucketScopeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteBucketScope")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(DeleteBucketScopeResponseObject); ok {
		if err := validResponse.VisitDeleteBucketScopeResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListBucketScopes operation middleware
func (sh *strictHandler) ListBucketScopes(ctx fiber.Ctx, bucket string) error {
	var request ListBucketScopesRequestObject

	request.Bucket = bucket

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.ListBucketScopes(ctx.Context(), request.(ListBucketScopesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListBucketScopes")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(ListBucketScopesResponseObject); ok {
		if err := validResponse.VisitListBucketScopesResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AddBucketScope operation middleware
func (sh *strictHandler) AddBucketScope(ctx fiber.Ctx, bucket string) error {
	var request AddBucketScopeRequestObject

	request.Bucket = bucket

	var body AddBucketScopeJSONRequestBody
	if err := ctx.Bind().Body(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.AddBucketScope(ctx.Context(), request.(AddBucketScopeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddBucketScope")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(AddBucketScopeResponseObject); ok {
		if err := validResponse.VisitAddBucketScopeResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteProjectData operation middleware
func (sh *strictHandler) DeleteProjectData(ctx fiber.Ctx, organization string, projectId string) error {
	var request DeleteProjectDataRequestObject

	request.Organization = organization
	request.ProjectId = projectId

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteProjectData(ctx.Context(), request.(DeleteProjectDataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteProjectData")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(DeleteProjectDataResponseObject); ok {
		if err := validResponse.VisitDeleteProjectDataResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
